/**
 * Professional salon titles/roles
 */
export const SALON_PROFESSIONAL_TITLES = [
  'Senior Stylist',
  'Master Stylist',
  'Junior Stylist',
  'Apprentice Stylist',
  'Hair Color Specialist',
  'Hair Extension Specialist',
  'Barber',
  'Senior Barber',
  'Nail Technician',
  'Senior Nail Technician',
  'Manicurist',
  'Pedicurist',
  'Esthetician',
  'Senior Esthetician',
  'Makeup Artist',
  'Senior Makeup Artist',
  'Massage Therapist',
  'Senior Massage Therapist',
  'Receptionist',
  'Salon Manager',
  'Assistant Manager',
  'Spa Therapist',
  'Senior Spa Therapist',
  'Brow Specialist',
  'Lash Specialist',
  'Waxing Specialist',
  'Hair Treatment Specialist',
  'Bridal Specialist',
  'Men\'s Grooming Specialist',
  'Kids\' Stylist',
] as const;

/**
 * Common salon skills/specializations
 */
export const SALON_SKILLS = [
  'Haircutting',
  'Hair Styling',
  'Hair Coloring',
  'Highlights',
  'Balayage',
  'Ombre',
  'Hair Extensions',
  'Hair Weaving',
  'Hair Braiding',
  'Hair Treatment',
  'Hair Repair',
  'Perm',
  'Straightening',
  'Keratin Treatment',
  'Hair Consultation',
  'Men\'s Haircut',
  'Fade',
  'Beard Trim',
  'Mustache Trim',
  'Shaving',
  'Manicure',
  'Pedicure',
  'Gel Nails',
  'Acrylic Nails',
  'Nail Art',
  'Nail Repair',
  'Facial Treatment',
  'Deep Cleansing',
  'Anti-Aging Treatment',
  'Acne Treatment',
  'Makeup Application',
  'Bridal Makeup',
  'Event Makeup',
  'Contouring',
  'Eyebrow Shaping',
  'Eyebrow Tinting',
  'Eyelash Extensions',
  'Eyelash Lifting',
  'Eyelash Tinting',
  'Waxing',
  'Brazilian Wax',
  'Bikini Wax',
  'Full Body Wax',
  'Threading',
  'Massage',
  'Deep Tissue Massage',
  'Swedish Massage',
  'Hot Stone Massage',
  'Aromatherapy',
  'Body Treatment',
  'Exfoliation',
  'Customer Service',
  'Product Knowledge',
  'Consultation',
  'Sales',
] as const;

export type SalonProfessionalTitle = typeof SALON_PROFESSIONAL_TITLES[number];
export type SalonSkill = typeof SALON_SKILLS[number];

